title: Ravi Teja Gonnabathula
logo: /assets/img/raviteja_gonnabathulla.jpg
description: Data Scientist 
#show_downloads: true
theme: jekyll-theme-minimal

markdown: kramdown
highlighter: rouge
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/
