title: Ravi Teja Gonnabathula
description: "Data Science Consultant"
logo: /assets/img/profile_pic.png
#show_downloads: true

theme: hyde

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
  url: ./
- text: Add a new page
  internal: true
  url: add-a-new-page
- text: Configure the Guide
  internal: true
  url: configure-the-guide
- text: GitHub Setup
  internal: true
  url: github
- text: Create a Glossary
  glossary: true
- text: Edit this Repo
  internal: false
  url: https://github.com/DCgov/guides-template
